######################################################################
# Automatically generated by qmake (1.07a) Tue Apr 20 11:30:45 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .

LIBS += -lGL \
    -lglut \
    -lGLU

# Input
HEADERS += Point2D.h Polygone.h tools.h
SOURCES += Point2D.cpp Polygone.cpp tools.cpp tp04.cpp
