######################################################################
# Automatically generated by qmake (2.01a) ven. avr. 30 01:10:49 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += OutilsPGM.h
SOURCES += OutilsPGM.cpp tp6.cpp
