######################################################################
# Automatically generated by qmake (1.07a) Thu Apr 29 11:28:19 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += OutilsPGM.h
SOURCES += main.cpp OutilsPGM.cpp
