######################################################################
# Automatically generated by qmake (2.01a) jeu. avr. 29 21:32:06 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += OutilsPGM.h
SOURCES += main.cpp OutilsPGM.cpp
