######################################################################
# Automatically generated by qmake (1.07a) Tue Apr 27 12:52:21 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += OutilsPGM.h
SOURCES += OutilsPGM.cpp tp6.cpp
