######################################################################
# Automatically generated by qmake (2.01a) ven. avr. 30 02:16:04 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += OutilsPGM.h
SOURCES += main.cpp OutilsPGM.c
